### ISSUE TITLE
Some kernel compilation issues.

### ISSUE THREAD

**Issue by Vxer-Lee** [polygraphene/DirtyPipe-Android#11]
Hello:
 I want to add some demo for reading and writing files in mymod.c, such as filp_open and kernel_read_file. I used the./build/build.sh file in your document and found an error:  "ERROR: modpost: "kernel_read_file" [../google-modules/mymod/mymod.ko] undefined!"  。

I don't have any driver development decompression, thank you!
![image](https://user-images.githubusercontent.com/27657137/170649331-28fbeb19-5b67-477d-b423-7712e0859e8b.png)

**Comment by polygraphene** [comment]
Try to add this if didn't.
```
#include <linux/kernel_read_file.h>
```
